{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nl-portal-backend.fullname" . }}
  labels:
    {{- include "nl-portal-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database
  DATABASE_PASSWORD: {{ .Values.settings.database.password | quote }}

  # Keycloak
  KEYCLOAK_TOKEN_EXCHANGE_SECRET: {{ .Values.settings.keycloak.tokenExchangeSecret | quote }}

  # Configuration Panel
  CONFIGURATION_PANEL_TOKEN: {{ .Values.settings.app.features.configurationPanel.token | quote }}

  # BesluitenAPI
  NLPORTAL_CONFIG_BESLUITENAPI_PROPERTIES_SECRET: {{ .Values.settings.services.besluitenapi.properties.secret | quote }}

  # CatalogiAPI
  NLPORTAL_CONFIG_CATALOGIAPI_PROPERTIES_SECRET: {{ .Values.settings.services.catalogiapi.properties.secret | quote }}

  # DocumentenAPIs â€“ OpenZaak + DummyDoc
  NLPORTAL_CONFIG_DOCUMENTENAPIS_PROPERTIES_CONFIGURATIONS_OPENZAAK_SECRET: {{ .Values.settings.services.documentenapis.properties.configurations.openzaak.secret | quote }}
  NLPORTAL_CONFIG_DOCUMENTENAPIS_PROPERTIES_CONFIGURATIONS_DUMMYDOC_SECRET: {{ .Values.settings.services.documentenapis.properties.configurations.dummydoc.secret | quote }}

  # ObjectenAPI
  NLPORTAL_CONFIG_OBJECTENAPI_PROPERTIES_TOKEN: {{ .Values.settings.services.objectenapi.properties.token | quote }}

  # OpenKlant
  NLPORTAL_CONFIG_OPENKLANT_PROPERTIES_SECRET: {{ .Values.settings.services.openklant.properties.secret | quote }}

  # OpenKlant2
  NLPORTAL_CONFIG_OPENKLANT2_PROPERTIES_TOKEN: {{ .Values.settings.services.openklant2.properties.token | quote }}

  # HaalCentraal BRP
  NLPORTAL_CONFIG_HAALCENTRAAL_BRP_PROPERTIES_APIKEY: {{ .Values.settings.services.haalcentraal_brp.properties.apiKey | quote }}
  NLPORTAL_CONFIG_HAALCENTRAAL_BRP_PROPERTIES_SSL_KEY_KEY: {{ .Values.settings.services.haalcentraal_brp.properties.ssl.key.key | quote }}
  NLPORTAL_CONFIG_HAALCENTRAAL_BRP_PROPERTIES_SSL_KEY_KEYPASSWORD: {{ .Values.settings.services.haalcentraal_brp.properties.ssl.key.keyPassword | quote }}
  NLPORTAL_CONFIG_HAALCENTRAAL_BRP_PROPERTIES_SSL_TRUSTEDCERTIFICATE: {{ .Values.settings.services.haalcentraal_brp.properties.ssl.trustedCertificate | quote }}

  # HaalCentraal HR
  NLPORTAL_CONFIG_HAALCENTRAAL_HR_PROPERTIES_APIKEY: {{ .Values.settings.services.haalcentraal_hr.properties.apiKey | quote }}
  NLPORTAL_CONFIG_HAALCENTRAAL_HR_PROPERTIES_SSL_KEY_KEY: {{ .Values.settings.services.haalcentraal_hr.properties.ssl.key.key | quote }}
  NLPORTAL_CONFIG_HAALCENTRAAL_HR_PROPERTIES_SSL_KEY_KEYPASSWORD: {{ .Values.settings.services.haalcentraal_hr.properties.ssl.key.keyPassword | quote }}
  NLPORTAL_CONFIG_HAALCENTRAAL_HR_PROPERTIES_SSL_TRUSTEDCERTIFICATE: {{ .Values.settings.services.haalcentraal_hr.properties.ssl.trustedCertificate | quote }}

  # Payment Direct
  NLPORTAL_CONFIG_PAYMENT_DIRECT_PROPERTIES_CONFIGURATIONS_BELASTINGZAKEN_APIKEY: {{ .Values.settings.services.payment.direct.properties.configurations.belastingzaken.apiKey | quote }}
  NLPORTAL_CONFIG_PAYMENT_DIRECT_PROPERTIES_CONFIGURATIONS_BELASTINGZAKEN_APISECRET: {{ .Values.settings.services.payment.direct.properties.configurations.belastingzaken.apiSecret | quote }}
  NLPORTAL_CONFIG_PAYMENT_DIRECT_PROPERTIES_CONFIGURATIONS_BELASTINGZAKEN_WEBHOOKAPIKEY: {{ .Values.settings.services.payment.direct.properties.configurations.belastingzaken.webhookApiKey | quote }}
  NLPORTAL_CONFIG_PAYMENT_DIRECT_PROPERTIES_CONFIGURATIONS_BELASTINGZAKEN_WEBHOOKAPISECRET: {{ .Values.settings.services.payment.direct.properties.configurations.belastingzaken.webhookApiSecret | quote }}

  # Payment Ogone
  NLPORTAL_CONFIG_PAYMENT_OGONE_PROPERTIES_SHAOUTPARAMETERS: {{ .Values.settings.services.payment.ogone.properties.shaOutParameters | quote }}
  NLPORTAL_CONFIG_PAYMENT_OGONE_PROPERTIES_CONFIGURATIONS_BELASTINGZAKEN_SHAINKEY: {{ .Values.settings.services.payment.ogone.properties.configurations.belastingzaken.shaInKey | quote }}
  NLPORTAL_CONFIG_PAYMENT_OGONE_PROPERTIES_CONFIGURATIONS_BELASTINGZAKEN_SHAOUTKEY: {{ .Values.settings.services.payment.ogone.properties.configurations.belastingzaken.shaOutKey | quote }}

  # ZakenAPI
  NLPORTAL_CONFIG_ZAKENAPI_PROPERTIES_SECRET: {{ .Values.settings.services.zakenapi.properties.secret | quote }}

{{- end }}
